AWSTemplateFormatVersion: "2010-09-09"

Resources:
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: queue
          AttributeType: S
        - AttributeName: day
          AttributeType: S
      KeySchema:
        - AttributeName: queue
          KeyType: HASH
        - AttributeName: day
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "テーブル名"
      Tags: 
        - Key: "intern"
          Value: "intern"
