AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: csvToDynamodbFunctionRule_biz
      ScheduleExpression: "cron(0 18 * * ? *)"
      State: ENABLED
      Targets:
        - Id: MyLambdaTarge
          Arn: arn:aws:lambda:ap-northeast-1:197753689022:function:csvToDynamodbFunction_biz